Refactored to use poetry instead of setup.py
mnoergaard/petprep_extract_tacs pull request #22
Opened 2024-11-26 17:52 UTC by bendhouseart

- Preserved entrypoint run.py for direct/unpackaged use
- Moved bids.py to utils folder to avoid circular import
- Moved functionality from run.py to extract_tacs.py
- Created cli() method in extract_tacs.py to provide entry point for poetry/package installation in lieu of __name__ == "main"
- bumped version to 0.0.4 to account for minor changes

2024-11-27 15:07 UTC, bendhouseart commented on petprep_extract_tacs/utils/merge_tacs.py
> +from petprep_extract_tacs.utils.bids import collect_participants
Swap with niworkflows and remove utils/bids.py entirely

2024-11-27 15:08 UTC, bendhouseart commented
Update README too! @bendhouseart

2024-11-27 16:35 UTC, bendhouseart commented on pyproject.toml
> +
Added entry points for `petprep_extract_tacs` and `merge_tacs` following install via pip.

2024-11-27 16:36 UTC, bendhouseart commented on pyproject.toml
> +niworkflows = "1.10.2"
Updated `niworkflows` to latest to ensure PET data was included when `utils.bids.collect_participants` and `utils.bids.collect_data` are called.

2024-11-27 16:37 UTC, bendhouseart commented on petprep_extract_tacs/utils/merge_tacs.py
> +    main()
Added explicit main function.

2024-11-27 16:39 UTC, bendhouseart commented on README.md
> +--bids_dir /bids_dir /output_dir participant --n_procs 4 system_platform=Darwin
Removed `--bids_dir` and `--output_dir` flags from README description, added in example of usage following pip install.

2024-11-27 16:40 UTC, bendhouseart commented on setup.py
> -)
Removed in favor of using `poetry build` instead, this stuff all makes sense to someone, but poetry "just works".

2024-11-27 16:40 UTC, bendhouseart commented on version
> -0.0.3
Moved to pyproject.toml.

2024-11-27 16:42 UTC, bendhouseart commented
Lastly, had to be more explicit and pass the `args` namespace object to the `init_<wf>` and other such objects following refactor of `petprep_extract_tacs` and move from `args` being global to a local var.

2024-12-02 10:02 UTC, mnoergaard requested changes
Overall, LGTM.

2024-12-02 10:02 UTC, mnoergaard commented on petprep_extract_tacs/utils/merge_tacs.py
> +from niworkflows.utils.bids import collect_participants, collect_data
great

2024-12-02 10:02 UTC, mnoergaard commented on setup.py
> -)
Let's do it your way :-)

2024-12-02 15:23 UTC, bendhouseart commented on README.md
> +--bids_dir /bids_dir /output_dir participant --n_procs 4 system_platform=Darwin
Weird, must have missed or merged in from main or something silly. Fixed.

2024-12-02 15:28 UTC, bendhouseart commented
Corrections applied, thanks for reviewing.

2024-12-02 15:28 UTC, bendhouseart commented on README.md
> +petprep_extract_tacs /path/to/your/bids/dataset /path/to/output/dir --n_procs 4 --wm
```suggestion
petprep_extract_tacs /path/to/your/bids/dataset /path/to/output/dir participant --n_procs 4 --wm
```

2024-12-02 15:30 UTC, bendhouseart commented on README.md
> +petprep_extract_tacs /path/to/your/bids/dataset /path/to/output/dir --n_procs 4 --wm
Weird, this looks fixed to me on commit 5fe7baed720291430, but appears s unchanged here on this review page.

2024-12-02 15:43 UTC, merged